apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deployment
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      initContainers:
      - name: db-migration
        image: postgres:latest
        env:
        - name: POSTGRESQL_DATABASE
          value: {{ .Values.postgresql.global.postgresql.auth.database }}
        - name: POSTGRESQL_USER
          value: {{ .Values.postgresql.global.postgresql.auth.username }}
        - name: PGPASSWORD  # Special env variables used for postgres
          value: {{ .Values.postgresql.global.postgresql.auth.password }}
        - name: POSTGRESQL_ENDPOINT
          value: {{ .Values.postgresqlEndpoint }}
        command: ['sh', '-c', 
            'until pg_isready -h $POSTGRESQL_ENDPOINT -p 5432; 
            do echo waiting for database; sleep 2; done;
            PGPASSWORD=$PGPASSWORD psql -h $POSTGRESQL_ENDPOINT -U $POSTGRESQL_USER -d $POSTGRESQL_DATABASE -c "CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\";"
            PGPASSWORD=$PGPASSWORD psql -h $POSTGRESQL_ENDPOINT -U $POSTGRESQL_USER -d $POSTGRESQL_DATABASE -c "CREATE TABLE IF NOT EXISTS todos (id UUID NOT NULL DEFAULT uuid_generate_v4(), text TEXT, checked BOOLEAN);"'
        ]
      containers:
      - name: todos
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.imagePullPolicy }}
        env:
        - name: POSTGRESQL_DATABASE
          value: {{ .Values.postgresql.global.postgresql.auth.database }}
        - name: POSTGRESQL_USER
          value: {{ .Values.postgresql.global.postgresql.auth.username }}
        - name: POSTGRESQL_PASSWORD
          value: {{ .Values.postgresql.global.postgresql.auth.password }}
        - name: POSTGRESQL_ENDPOINT
          value: {{ .Values.postgresqlEndpoint }}
        - name: DB_URL
          value: "postgres://$(POSTGRESQL_USER):$(POSTGRESQL_PASSWORD)@$(POSTGRESQL_ENDPOINT):5432/$(POSTGRESQL_DATABASE)?sslmode=disable"
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 10 }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        ports:
        - name: app-port
          containerPort: 3000