apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Chart.Name }}-service-monitor
  labels:
    app.kubernetes.io/part-of: {{ .Chart.Name }}-sm
spec:
  endpoints:
    - interval: 15s
      port: metrics
      scrapeTimeout: 14s
  selector:
    matchLabels:
      app.kubernetes.io/part-of: {{ .Chart.Name }}-sm