apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  annotations:
    prometheus.io/port: "metrics"
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/part-of: {{ .Release.Name }}-sm
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
  - name: app-port
    protocol: TCP
    port: 80
    targetPort: 3000
  - name: metrics
    protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP