apiVersion: v2
name: todos
description: todo App Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: postgresql
    version: "14.3.3"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    condition: postgresql.enabled
  # - name: prometheus-operator-crds
  #   version: "10.0.0"
  #   repository: "https://prometheus-community.github.io/helm-charts"
  #   condition: prometheus-operator-crds.enabled
  - name: kube-prometheus
    version: "8.30.1"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    condition: kube-prometheus.enabled