kube-prometheus:
  enabled: true
# prometheus-operator-crds:
#   enabled: true

postgresql:
  enabled: true
  volumePermissions:
    enabled: true
  global:
    postgresql:
      auth:
        username: USERNAME
        password: PASSWORD
        database: "todos-db"

image:
  repository: todos
  tag: IMAGE_TAG
  imagePullPolicy: Never
resources:
  requests:
    memory: "128Mi"
    cpu: "50m"
  limits:
    memory: "512Mi"
    cpu: "250m"
livenessProbe:
  httpGet:
    path: /alive
    port: 8080
  initialDelaySeconds: 15
  periodSeconds: 10