kube-prometheus:
  enabled: true
# prometheus-operator-crds:
#   enabled: true

postgresql:
  enabled: true
  volumePermissions:
    enabled: true
  global:
    postgresql:
      auth:
        username: USERNAME
        password: PASSWORD
        database: "todos-db"

postgresqlEndpoint: todos-postgresql.default.svc.cluster.local
image:
  repository: todos
  tag: IMAGE_TAG
  imagePullPolicy: Never