name: Deploy App in KinD

on:
  push:
    branches:
      - 'main'
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag todos:${{ github.sha }}
    - name: Save Docker image as tarball
      run: docker save -o /tmp/todos.tar todos:${{ github.sha }}
    - name: Upload Docker image as artifact
      uses: actions/upload-artifact@v2
      with:
        name: docker-image
        path: /tmp/todos.tar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Docker image tarball artifact
        uses: actions/download-artifact@v2
        with:
          name: docker-image
          path: /tmp
      - name: Load Docker image from tarball
        run: |
          docker load --input /tmp/todos.tar
          docker image ls -a
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1 
      - name: Run KinD commands
        run: |
          kind version
          kind get clusters
          kind load docker-image todos:${{ github.sha }} --name chart-testing
      - name: Copying helm chart from repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: 'helm-charts'
          sparse-checkout-cone-mode: false
      - name: Install helm charts
        run: |
          helm version
          sed -i 's/USERNAME/${{ secrets.DB_USERNAME }}/g' helm-charts/todo/values.yaml
          sed -i 's/PASSWORD/${{ secrets.DB_PASSWORD }}/g' helm-charts/todo/values.yaml
          sed -i 's/IMAGE_TAG/${{ github.sha }}/g' helm-charts/todo/values.yaml
          helm install todos helm-charts/todo/
          kubectl get all
          echo "++++++++++++++++++++++++++++++++++++++++++"
          echo "++++++++++++++++++++++++++++++++++++++++++"
          sleep 300
          kubectl get all
